# Url to a Solana RPC cluster.
url = "https://api.devnet.solana.com"
# Path to the program's shared object file.
program_so = "./program.so"

[options]
# How many threads can be used to send WriteBuffer transactions.
jobs = 8
# Seconds to sleep in between RPC requests.
sleep = 100
# RPC client configured timeout.
timeout = 30
# RPC client configured max_retries.
max_retries = 9000

[keypairs]
# Path to the program's keypair file.
program = "./program-keypair.json"
# Path to the program's update authority keypair file.
authority = "./payer.json"

